# NumPy 

NumPy is a general-porpuse array-proccesing pakage. it provide a multidimentional array object and tools working these arra.
    it is a fundamental pakege of scintific computing with python

- what is an Array?
array is a data structure that store values with same datatype

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3,4,5,6]

arr=np.array(my_list)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr.shape

(6,)

In [15]:
my_lst1=[1,2,3,4]
my_lst2=[5,6,7,8]
my_lst3=[9,0,1,2]

arr=np.array([my_lst1, my_lst2, my_lst3])

In [16]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [8]:
arr.shape

(3, 4)

In [9]:
arr.reshape(4, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

### Indexing

In [13]:
arr=np.array([1,2,3,4,5,6])

In [14]:
arr[3]

4

In [17]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [18]:
arr[:,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [33]:
arr[1:3,1:3]

array([[6, 7],
       [0, 1]])

In [34]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [37]:
arr[1:3,1:4]

array([[6, 7, 8],
       [0, 1, 2]])

In [43]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [45]:
arr[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [47]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [51]:
arr[1:2,1:3]

array([[6, 7]])